ALTER TABLE diagnostic_parameters 
ADD COLUMN IF NOT EXISTS ref_min_male NUMERIC(10,4),
ADD COLUMN IF NOT EXISTS ref_max_male NUMERIC(10,4),
ADD COLUMN IF NOT EXISTS ref_min_female NUMERIC(10,4),
ADD COLUMN IF NOT EXISTS ref_max_female NUMERIC(10,4),
ADD COLUMN IF NOT EXISTS ref_min_child NUMERIC(10,4),
ADD COLUMN IF NOT EXISTS ref_max_child NUMERIC(10,4);
