ALTER TABLE diagnostic_parameters 
ADD COLUMN IF NOT EXISTS ref_min_male VARCHAR(100),
ADD COLUMN IF NOT EXISTS ref_max_male VARCHAR(100),
ADD COLUMN IF NOT EXISTS ref_min_female VARCHAR(100),
ADD COLUMN IF NOT EXISTS ref_max_female VARCHAR(100),
ADD COLUMN IF NOT EXISTS ref_min_child VARCHAR(100),
ADD COLUMN IF NOT EXISTS ref_max_child VARCHAR(100);
